name: Test API Documentation Workflow

on:
  push:
    branches: [deploy]

jobs:
  test-alps:
    uses: ./.github/workflows/apidoc.yml
    with:
      format: 'alps'
      alps-profile: 'docs/alps.json'
      docs-path: 'docs/api'
      publish-to: 'artifact-only'
